### ISSUE TITLE
incr("key") does not seem to work

### ISSUE THREAD

**Issue by szabgab** [cosimo/perl6-cache-memcached#8]
The README inicates it should but when I try it I get:

use v6;
use Cache::Memcached;

my $memd = Cache::Memcached.new;

say $memd.incr("counter");

```
Too few positionals passed; expected 3 arguments but got 2
```

This is Rakudo version 2017.06 built on MoarVM version 2017.06
same with 
This is Rakudo version 2017.07 built on MoarVM version 2017.07

**Comment by jonathanstowe** [comment]
There was no default on the value and it wasn';t being tested.
