### ISSUE TITLE
Allow initial value for incr and decr

### ISSUE THREAD

**Issue by szabgab** [cosimo/perl6-cache-memcached#9]
It might be nice to allow a third parameter to be used in `incr` to set the key to that value in case the key did not exist:

```
$memd.incr("counter", 1, :init(1));
```

https://metacpan.org/pod/Memcached::Client allows for that.

**Comment by jonathanstowe** [comment]
One question about this, if the key *does* exist  but isn't an integer should it still return an error if an initialiser is supplied?  I'm thinking it should so there is less surprise but ymmv.

**Comment by szabgab** [comment]
I think so too.
